
module.exports = `
// Do not edit this file.

// Import variables from css module
export const atomized{{AtomName}} = require('{{atomFilePath}}')

// Generated typed list of exported variables
type TExportedVariables = {{properties}}

// Accepted atom return format
type TReturnFormat = 'raw'|'value'|'unit'|'array'

/**
 * Get an atom value from atoms module file.
 * @param property Property name to get.
 * @param format Parse CSS values, ex for 144px, extract unit from value.
 */
export function getAtomized{{AtomName}} ( property:TExportedVariables, format:TReturnFormat = 'raw' ) {
	// Return full value
	const value = atomized{{AtomName}}[ property ]
	if ( format == 'raw' )
		return value
	// Split digital from alpha chars
	const split = value.match(/(\d*\.?\d*)(.*)/)
	if ( format == 'value' )
		return parseFloat( split[ 1 ] )
	else if ( format == 'unit' )
		return split[ 2 ].toLowerCase()
	else if ( format == 'array' )
		return split;
}
`